//! MCP server handler, resources, and stdio transport entry point.

use rmcp::{
    ErrorData as McpError, RoleServer, ServerHandler, ServiceExt,
    model::{
        Implementation, ListResourceTemplatesResult, ListResourcesResult, PaginatedRequestParams,
        ReadResourceRequestParams, ReadResourceResponse, ReadResourceResult, Resource,
        ResourceContents, ResourceTemplate, ServerCapabilities, ServerInfo,
    },
    prompt_handler,
    service::RequestContext,
    tool_handler,
    transport::stdio,
};
use serde_json::json;

use crate::db::Database;
use crate::models::{AssetQuery, DEFAULT_ASSET_QUERY_LIMIT};

/// Read-only MCP facade over a watcher database.
#[derive(Clone)]
pub struct WatcherMcp {
    /// Opened watcher database.
    pub(super) db: Database,
}

impl WatcherMcp {
    /// Build an MCP server bound to an already-migrated database.
    ///
    /// # Arguments
    /// - `db`: Cloneable watcher database handle.
    ///
    /// # Returns
    /// Server that can be served over stdio or an in-memory transport.
    ///
    /// # Examples
    /// ```
    /// # use watcher::db::Database;
    /// # use watcher::mcp::WatcherMcp;
    /// # let dir = tempfile::tempdir()?;
    /// # let db = Database::open(&dir.path().join("watcher.db"))?;
    /// # db.migrate()?;
    /// let _server = WatcherMcp::new(db);
    /// # Ok::<(), anyhow::Error>(())
    /// ```
    pub fn new(db: Database) -> Self {
        Self { db }
    }

    /// Names of tools generated by `#[tool_router]`.
    ///
    /// # Arguments
    /// none
    ///
    /// # Returns
    /// Tool names in router order.
    ///
    /// # Examples
    /// ```
    /// # use watcher::mcp::{TOOL_NAMES, WatcherMcp};
    /// let names = WatcherMcp::tool_names();
    /// assert!(TOOL_NAMES.iter().all(|name| names.iter().any(|item| item == name)));
    /// ```
    pub fn tool_names() -> Vec<String> {
        Self::tool_router()
            .list_all()
            .into_iter()
            .map(|tool| tool.name.to_string())
            .collect()
    }

    /// Names of prompts generated by `#[prompt_router]`.
    ///
    /// # Arguments
    /// none
    ///
    /// # Returns
    /// Prompt names in router order.
    ///
    /// # Examples
    /// ```
    /// # use watcher::mcp::{PROMPT_NAMES, WatcherMcp};
    /// let names = WatcherMcp::prompt_names();
    /// assert!(PROMPT_NAMES.iter().all(|name| names.iter().any(|item| item == name)));
    /// ```
    pub fn prompt_names() -> Vec<String> {
        Self::prompt_router()
            .list_all()
            .into_iter()
            .map(|prompt| prompt.name)
            .collect()
    }
}

/// Serve the watcher inventory over MCP stdio.
///
/// stdout is reserved for JSON-RPC. Callers must initialize logging to stderr
/// before entering this function.
///
/// # Arguments
/// - `db`: Opened and migrated watcher database.
///
/// # Returns
/// `Ok(())` after the MCP client disconnects.
///
/// # Errors
/// Returns an error if the stdio transport or MCP handshake fails.
///
/// # Examples
/// ```text
/// watcher::mcp::run_stdio(db).await?;
/// ```
pub async fn run_stdio(db: Database) -> anyhow::Result<()> {
    tracing::info!("watcher MCP server listening on stdio");
    let service = WatcherMcp::new(db).serve(stdio()).await?;
    service.waiting().await?;
    Ok(())
}

#[tool_handler]
#[prompt_handler]
impl ServerHandler for WatcherMcp {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
                .enable_prompts()
                .enable_resources()
                .build(),
        )
        .with_server_info(Implementation::from_build_env())
        .with_instructions(
            "watcher is a local asset-monitoring inventory. \
             Use tools to inspect confirmed-live ports, HTTP(S) services, URL status, alerts, and findings. \
             Only plan authorized testing against assets watcher has already marked live. \
             This server is read-only and does not scan or exploit targets.",
        )
    }

    async fn list_resources(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, McpError> {
        Ok(ListResourcesResult::with_all_items(vec![
            resource("watcher://snapshot", "Inventory snapshot"),
            resource("watcher://live/ports", "Live open TCP ports"),
            resource("watcher://live/web", "Live HTTP(S) services"),
            resource("watcher://live/urls", "Live 2xx/3xx URLs"),
            resource("watcher://systems", "Business systems"),
        ]))
    }

    async fn list_resource_templates(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListResourceTemplatesResult, McpError> {
        Ok(ListResourceTemplatesResult::with_all_items(vec![
            ResourceTemplate::new("watcher://system/{name}", "system-context")
                .with_description("Live and web context for one business system")
                .with_mime_type("application/json"),
        ]))
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResponse, McpError> {
        let query = AssetQuery {
            system: None,
            keyword: None,
            limit: DEFAULT_ASSET_QUERY_LIMIT,
            offset: 0,
        };

        let payload = match request.uri.as_str() {
            "watcher://snapshot" => encode_resource(self.db.dashboard_snapshot())?,
            "watcher://live/ports" => encode_resource(self.db.list_open_ports_filtered(&query))?,
            "watcher://live/web" => encode_resource(self.db.list_web_services_filtered(&query))?,
            "watcher://live/urls" => encode_resource(self.db.list_live_urls_filtered(&query))?,
            "watcher://systems" => encode_resource(self.db.list_system_summaries(&query))?,
            uri if let Some(name) = system_resource_name(uri) => {
                encode_resource(self.db.system_context(name, &query))?
            }

            _ => {
                return Err(McpError::resource_not_found(
                    "resource_not_found",
                    Some(json!({ "uri": request.uri })),
                ));
            }
        };
        Ok(ReadResourceResult::new(vec![ResourceContents::text(payload, &request.uri)]).into())
    }
}

/// Build a named watcher resource descriptor.
///
/// # Arguments
/// - `uri`: Resource URI.
/// - `name`: Short display name.
///
/// # Returns
/// Annotated MCP resource.
fn resource(uri: &str, name: &str) -> Resource {
    Resource::new(uri, name).with_mime_type("application/json")
}

/// Extract `{name}` from `watcher://system/{name}`.
///
/// # Arguments
/// - `uri`: Concrete resource URI.
///
/// # Returns
/// System name when the URI matches the template.
fn system_resource_name(uri: &str) -> Option<&str> {
    uri.strip_prefix("watcher://system/")
        .map(str::trim)
        .filter(|name| !name.is_empty() && !name.contains('/'))
}

/// Encode a resource payload as pretty JSON.
///
/// # Arguments
/// - `result`: Fallible serializable value.
///
/// # Returns
/// Pretty JSON text.
///
/// # Errors
/// Returns an MCP error if the query or JSON encoding fails.
fn encode_resource<T: serde::Serialize>(result: anyhow::Result<T>) -> Result<String, McpError> {
    let value = result.map_err(|err| McpError::internal_error(err.to_string(), None))?;
    serde_json::to_string_pretty(&value).map_err(|err| {
        McpError::internal_error(format!("failed to encode resource json: {err}"), None)
    })
}
